# paramenters for the model
# key: val
# Parameters for training
AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
# pre-trained model.... we want to train the custom layer only
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2
WEIGHTS: 'imagenet'
LEARNING_RATE: 0.01